<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Compare</name>
   <tag></tag>
   <elementGuidId>4094d2a4-6658-48f8-95cb-0f5044a17475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.CustomInputGroup---submit---2U56h.btn.btn-default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f174b34a-906c-48a1-b4e1-67b653e9a807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>382e903a-9c3e-4208-a121-92ea52597cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success CustomInputGroup---submit---2U56h btn btn-default</value>
      <webElementGuid>1c0576e8-486e-49e7-b33e-451bc31fb263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare</value>
      <webElementGuid>e3af95ee-1393-40e5-9ecd-be539e46372a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;Transactions---withSide---2taIP container-fluid Transactions---summaryContainer---1rNvj&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[2]/div[@class=&quot;row TransferOverseaTypeContainer---container---3myRn&quot;]/div[@class=&quot;TransferOverseaTypeContainer---fixContainer---24R7Q&quot;]/div[@class=&quot;col-xs-12 col-md-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 undefined&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;CustomInputGroup---container---2Lt0m&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex-row&quot;]/div[@class=&quot;flex-col-xs-12 flex-col-sm flex-col-md flex-col-lg-2 CustomInputGroup---btnContainer---2KukB&quot;]/button[@class=&quot;btn btn-success CustomInputGroup---submit---2U56h btn btn-default&quot;]</value>
      <webElementGuid>a9f8efe5-5a3c-4f8f-abc5-596180092d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>62d7af12-52d9-4664-b03b-e94d20785a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[2]/div[2]/div/div[2]/div/div/div/form/div/div/div/div/div/div[4]/button</value>
      <webElementGuid>871a9857-e35d-4bfb-9c98-bfa3611f3c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[2]/following::button[1]</value>
      <webElementGuid>83541c3d-4fcf-4c05-a307-729391baf404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert To'])[1]/following::button[2]</value>
      <webElementGuid>2d16d297-ca78-4c3b-bf95-dc54b35c2622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>db9d6d79-d4c5-45e0-b3f8-69fbb7b8f57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Compare' or . = 'Compare')]</value>
      <webElementGuid>d55694db-53e8-4976-a7e6-72ec4d7a3509</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
