<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone No_benContactNationalNo</name>
   <tag></tag>
   <elementGuidId>19dc4108-8961-446b-9cb9-e0152c43b03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benContactNationalNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benContactNationalNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41b5f89d-5e26-4edc-979b-0200144576fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>afbe8cee-c59b-48cd-9f04-ac28ac87f233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23c6d0d8-f183-4dbf-a39d-ea197d2d442a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>1ed1436c-18ea-4c9a-8e7e-fa0286bffbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benContactNationalNo</value>
      <webElementGuid>f432ba8d-3911-46e3-b01b-2bec12f415a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Phone No.</value>
      <webElementGuid>e6f375d2-e522-4845-84b5-3753226454ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benContactNationalNo&quot;)</value>
      <webElementGuid>29b816af-6786-4c7c-abe7-41163beb1e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benContactNationalNo']</value>
      <webElementGuid>56c713a7-8bc2-4bdc-a46d-5a9c32ae07f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>8680a87d-91db-4a21-86b2-3384ba352c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>51a804f0-f3fb-4542-aba4-2bad7337f023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benContactNationalNo' and @title = 'Please Enter a Valid Phone No.']</value>
      <webElementGuid>8ad1a358-1840-48da-bc50-de3d957dd322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
