<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City (Destination)_benCity</name>
   <tag></tag>
   <elementGuidId>76a4a2ed-cf91-438b-a592-7f810ebabe88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>537e9243-94fd-40db-bcc3-bccc788ec23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>8962dbf3-6285-493b-984c-fdb469027c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bcf50c2-332f-4f46-9710-0aa19aba31c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f58715af-6cce-4fe2-af44-17023e53cc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benCity</value>
      <webElementGuid>1a13003b-223f-4341-98b0-9177c2eb42a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid City (Destination)</value>
      <webElementGuid>a1f20415-2927-4c7c-bdd1-37fac749eff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benCity&quot;)</value>
      <webElementGuid>7b715818-030a-4797-983e-f3cdf93c059f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benCity']</value>
      <webElementGuid>a683909a-abb0-4390-9be6-e153163b4182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[8]/div/div[2]/input</value>
      <webElementGuid>c87fa0cd-4733-47cc-900d-f40a2a296a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[8]/div/div[2]/input</value>
      <webElementGuid>cb65159e-ec74-420d-92e5-706a9b985c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benCity' and @title = 'Please Enter a Valid City (Destination)']</value>
      <webElementGuid>460096f8-e53d-44d0-acb0-eca3d3d20055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
