<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hello_my-password-input</name>
   <tag></tag>
   <elementGuidId>4e3f666c-7abc-40f1-b4d3-b1e02230ae62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#my-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='my-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb3d21f2-e154-4eaa-bb89-2b3ffb530206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6479f333-d05c-4b02-bb43-0a7246ec343a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>My Password</value>
      <webElementGuid>fab8f4dd-d47b-47bf-9bbf-89b7a2465fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>my-password-input</value>
      <webElementGuid>b51d5c94-4bac-4046-916c-efa527b74b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SecurityPhrase---login-input---AwPq0 SecurityPhrase---login-input-font---14Asi</value>
      <webElementGuid>6281a085-b25d-401a-9075-bf170b8bc4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>my-guid</name>
      <type>Main</type>
      <value>2acf0148-7c06-4fcd-aa02-cfb65073f0b6</value>
      <webElementGuid>3e35d91b-0358-44a0-9863-b3ef0e7bb08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>edf0ab14-6bc1-41a7-b6d4-8b7a9c182a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>286a6723-6614-4d75-ad28-772f11214b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2e0f71ff-3096-4cbf-90fd-37867b168bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c55b707c-2cbc-426b-90ba-d7d6e8dcf665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0432d4db-76e0-4e66-88bb-221a03811eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-password-input&quot;)</value>
      <webElementGuid>44d526c3-9658-4b5e-8fb1-bf297135a16f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='my-password-input']</value>
      <webElementGuid>33af117e-ca19-43e7-a03c-4e58c60165b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>6224fd6d-6842-4515-9112-57839ae931e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3b935965-a5a0-4cad-81e6-7083bcfe8d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'My Password' and @id = 'my-password-input']</value>
      <webElementGuid>acf624bc-99e7-486c-834c-409c34a738dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
