<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_benFirstName</name>
   <tag></tag>
   <elementGuidId>e40f002a-2137-48bb-b240-1c5aa90b5d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8eeffc3-7781-4a7c-9022-4ac0afbe15b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>ae84b20f-a937-4213-a292-27e08d4a5fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e740a6b0-e03c-47c1-a517-4214ee36be76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>2d19c88a-be91-42a8-bf2c-4597d5554eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benFirstName</value>
      <webElementGuid>14dc4971-d01f-4add-90dc-be56211da836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid First Name</value>
      <webElementGuid>d6061858-2b3a-431a-b927-2c04bc9ce873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benFirstName&quot;)</value>
      <webElementGuid>bf320068-4117-4bfc-b0e8-25485d9e5572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benFirstName']</value>
      <webElementGuid>852e075a-fe03-49a0-8065-c36b45ea01cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>ca23a4ab-443b-4045-b144-1d68fe7ddff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>2194861a-efdf-471d-99e6-fe1e986a9ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benFirstName' and @title = 'Please Enter a Valid First Name']</value>
      <webElementGuid>2ce9f7f9-e8c3-4393-bd7e-1b924d051562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
