<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_benLastName</name>
   <tag></tag>
   <elementGuidId>814b13b3-a921-4655-8683-9c5cb0c36d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>590e04d4-8e47-48c5-bd3d-c10b5914199e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>c2c91abe-97c5-4d7e-b33e-b8048fe6cefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>701ee6f4-3f60-456c-893b-a63da286e219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>a9025f7d-3953-45e4-9414-6ea73998d5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benLastName</value>
      <webElementGuid>d8e2e691-983f-48ea-b32f-25f6e551e056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Last Name</value>
      <webElementGuid>566d5bb7-b09f-4555-bd01-35322d0963d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benLastName&quot;)</value>
      <webElementGuid>dffa3283-81d4-4b1e-ae57-5adb4c305393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benLastName']</value>
      <webElementGuid>d5d32b3c-9b8c-458f-81ec-4a7621364033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>5924bf27-b5f5-4930-9105-dd93ce7c118e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>98552c9b-74b1-4b9a-93bf-3e75b3527167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benLastName' and @title = 'Please Enter a Valid Last Name']</value>
      <webElementGuid>d54fad5f-764e-450b-b3eb-8bed04ba0ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
