<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State_benState</name>
   <tag></tag>
   <elementGuidId>5d440478-a722-4cfa-ad16-878690e49fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benState</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7f93219-cd79-42c0-aa04-dc1d4fb742d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>e800877d-e4b7-4980-81f1-380c871f8568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d7fc591-b7b7-4a01-930f-3847120dd729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>26dcd504-81ed-44ab-a461-ae1f4f4f712f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benState</value>
      <webElementGuid>8404529e-8637-4ad0-81d2-085aa0463f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid State</value>
      <webElementGuid>d47105a3-044c-491e-8e2d-b2b97ea7df60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benState&quot;)</value>
      <webElementGuid>bb3b7c37-6a29-4beb-87a3-219c982bf8ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benState']</value>
      <webElementGuid>8da0cfd1-c98b-469b-bafa-b2d90c715562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[9]/div/div[2]/input</value>
      <webElementGuid>6e7c0124-cb9b-45cc-957e-a3b40c1956b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[9]/div/div[2]/input</value>
      <webElementGuid>eb2ab815-5834-4345-a4ec-e724b00d8ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benState' and @title = 'Please Enter a Valid State']</value>
      <webElementGuid>d83421aa-15a4-4df6-a3e1-5d74fcfc7ae5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
