<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal Code_benPostalCode</name>
   <tag></tag>
   <elementGuidId>d8bb7033-b08a-49aa-b9b8-3a80848ec5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benPostalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4097b89d-d161-44da-b975-c9ab0c5a50df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>9cfdc87f-4b04-4a84-8618-643ca841e5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c443de1a-71e6-4cdb-bbf0-d4f3ba724c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>ae653213-ce71-4e8c-9c95-2c2bdd844080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benPostalCode</value>
      <webElementGuid>0526c447-e49f-4fac-9df5-6240e00fb057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Postal Code</value>
      <webElementGuid>15b8923d-de53-47f2-83bd-4491f5de7fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benPostalCode&quot;)</value>
      <webElementGuid>11b89218-acab-4f79-b767-88e607ec48d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benPostalCode']</value>
      <webElementGuid>24cc21f8-0a66-4487-9633-075dd9a8f162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[7]/div/div[2]/input</value>
      <webElementGuid>5bdae764-b471-4166-9d66-135e3bd937b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[7]/div/div[2]/input</value>
      <webElementGuid>ab9046fc-d45e-4f61-83ff-215734aec431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benPostalCode' and @title = 'Please Enter a Valid Postal Code']</value>
      <webElementGuid>29285b53-757b-47a7-ab53-bebb5a46022b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
