<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jalan Sempurna Lubuk Pa</name>
   <tag></tag>
   <elementGuidId>18548396-6136-495a-a0f5-a563ca81e96d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='benStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e86c3ad9-bf97-47d3-8c03-dac424c0e96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---textArea---2iiJf</value>
      <webElementGuid>026bef0f-8b6e-43aa-89b6-9c3b5b1e842d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benStreet</value>
      <webElementGuid>90e6eadb-9116-4268-b9ab-60406e3664e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>eb22a09c-dc63-4f3e-b088-f456a77cdaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fbe6d756-53e5-44dc-b442-e72978330f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalan Sempurna Lubuk Pa</value>
      <webElementGuid>f580db20-f902-4c6a-aef7-3add4c0f7546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benStreet&quot;)</value>
      <webElementGuid>4d1ed33a-8588-4b0b-934b-4e136844ac1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='benStreet']</value>
      <webElementGuid>6f126501-e2e1-4df5-8745-f21a25126bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>9d905dcc-6e29-460b-a44d-90de5e38a618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 1'])[1]/following::textarea[1]</value>
      <webElementGuid>011971dc-6980-414b-b1ae-0b31f6077ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::textarea[1]</value>
      <webElementGuid>d18f39c2-5c08-428b-88bd-6c2de0da73ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 2'])[1]/preceding::textarea[1]</value>
      <webElementGuid>591b63a9-a593-4a34-b2b7-c47947ffe5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::textarea[2]</value>
      <webElementGuid>47c9b318-6b50-4b7c-97d9-09a857801536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jalan Sempurna Lubuk Pa']/parent::*</value>
      <webElementGuid>38a213b0-0bb4-49eb-a079-50abc7219563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>e0e2a724-05af-4ef2-8d34-f1af8cab8d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'benStreet' and (text() = 'Jalan Sempurna Lubuk Pa' or . = 'Jalan Sempurna Lubuk Pa')]</value>
      <webElementGuid>1b551ccb-e8c2-428a-82a0-3b0bb478e996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
