<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jalan Sempurna Lub</name>
   <tag></tag>
   <elementGuidId>597d72d1-42e6-42dc-8225-1456065f4add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='benStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14a763d8-2d8b-4c59-acb1-94be421fc890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---textArea---2iiJf</value>
      <webElementGuid>0b6a3c62-6960-43dd-a5c9-6b90ccddfa94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benStreet</value>
      <webElementGuid>4f8e1533-6aa0-4585-92fb-e2f8ee745066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f9a8c13a-f31f-49f7-b042-60745ffe98e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7fccc516-a8f2-426b-8ce4-9aeea19c78e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalan Sempurna Lub</value>
      <webElementGuid>38e05d46-8612-4c35-9a82-2de1927d446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benStreet&quot;)</value>
      <webElementGuid>cdf99bdd-0661-48fd-a840-a181081dec91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='benStreet']</value>
      <webElementGuid>2c59209a-bfc7-45af-842a-792bd2d701ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>d40d691e-737e-494e-9fad-a1795d034665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 1'])[1]/following::textarea[1]</value>
      <webElementGuid>a702cc8b-6c84-426f-901f-6ee32ec28983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::textarea[1]</value>
      <webElementGuid>247b157d-4537-4e0f-a01d-17bc4eb23e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 2'])[1]/preceding::textarea[1]</value>
      <webElementGuid>757cf63d-d8eb-49dd-b8da-9f8e45c8eac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::textarea[2]</value>
      <webElementGuid>ba8954b6-fd49-4ddd-adac-dda33ea03671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jalan Sempurna Lub']/parent::*</value>
      <webElementGuid>44a95278-3c6a-41fe-9c33-9967cc1f1ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>5fffa316-bc2f-4c6c-8ba5-3da0b7a067f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'benStreet' and (text() = 'Jalan Sempurna Lub' or . = 'Jalan Sempurna Lub')]</value>
      <webElementGuid>3a45e647-95bd-49f6-8434-c55668873683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
