<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TRANSFER</name>
   <tag></tag>
   <elementGuidId>e6784510-60f1-4a06-8f91-0db086a32920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cb861cd-c605-4a3d-8410-baaa43a2800c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PayNavigation---typeName---3lyPM</value>
      <webElementGuid>7c28f23b-57b4-4fb8-b801-25ac5f14bc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>bddbf4d1-a7e0-4be4-99e8-6b3dcd9b3a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;container-fluid PayNavigation---container---3nMJB&quot;]/div[@class=&quot;PayNavigation---navigation---3RD23&quot;]/div[@class=&quot;PayNavigation---navigationContent---2M_93 col-lg-8 col-md-10 col-xs-12&quot;]/div[@class=&quot;PayNavigation---row---3Pgej PayNavigation---mobile---wdWul&quot;]/div[@class=&quot;PayNavigation---nav-tabs---pHNAS&quot;]/div[@class=&quot;PayNavigation---desktopcontainer---4iWXT&quot;]/div[@class=&quot;PayNavigation---typeName---3lyPM&quot;]</value>
      <webElementGuid>88af6202-c043-4d5d-9e3c-628ae00bb6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8aaf6fa6-1985-4335-8028-14b16ae2f91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PayNavigation---typeName---3lyPM</value>
      <webElementGuid>c6f3580a-f5df-4da1-97e4-af70bb3ea649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>2d374de2-e10f-4824-b488-58224c6eeab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;container-fluid PayNavigation---container---3nMJB&quot;]/div[@class=&quot;PayNavigation---navigation---3RD23&quot;]/div[@class=&quot;PayNavigation---navigationContent---2M_93 col-lg-8 col-md-10 col-xs-12&quot;]/div[@class=&quot;PayNavigation---row---3Pgej PayNavigation---mobile---wdWul&quot;]/div[@class=&quot;PayNavigation---nav-tabs---pHNAS&quot;]/div[@class=&quot;PayNavigation---desktopcontainer---4iWXT&quot;]/div[@class=&quot;PayNavigation---typeName---3lyPM&quot;]</value>
      <webElementGuid>569d6f7f-2e97-4154-8ef1-fab9b20133fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>c0e19511-0b74-4186-87c0-4404f901fece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAY'])[1]/following::div[3]</value>
      <webElementGuid>e0835cb3-7965-43a9-a94d-b42c5d31076f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RELOAD'])[1]/preceding::div[1]</value>
      <webElementGuid>79acb8db-ac18-497f-b2c3-942cc727ac8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TABUNG HAJI'])[1]/preceding::div[4]</value>
      <webElementGuid>39140129-394c-42e9-9f1b-2ffccf8899b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRANSFER']/parent::*</value>
      <webElementGuid>97695154-0f16-4c96-b339-f3c6b38d0f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>1f7f12e0-478a-42ee-85b7-a341a6c5cdcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TRANSFER' or . = 'TRANSFER')]</value>
      <webElementGuid>a1745efa-801f-44ee-925d-b069b655751a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
