<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Check your Secure2u registered device an_fd105e</name>
   <tag></tag>
   <elementGuidId>49f54e89-c09f-437f-a83f-895edccce2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.OneTimePassword---header4---1PWZR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div[2]/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>9f29cae7-2bff-40d8-88d7-6536a584965f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OneTimePassword---header4---1PWZR</value>
      <webElementGuid>ed24626c-5430-4c48-8570-26d319a455a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check your Secure2u registered device and approve it within 50 seconds…</value>
      <webElementGuid>bb77dedd-76e1-4aad-852b-f6c7a34fe325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[@class=&quot;Transactions---content---2P7lC&quot;]/div[@class=&quot;Transactions---withSide---2taIP container-fluid Transactions---summaryContainer---1rNvj undefined&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;Transactions---stickyConfirmation---2aISx&quot;]/div[1]/div[@class=&quot;OneTimePassword---otp-wrapper---2Ykbh OneTimePassword---slide---2IJwL put-in-modal&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 col-md-8 col-sm-12 col-xs-12&quot;]/div[@class=&quot;OneTimePassword---verification-content---2oWKu&quot;]/h4[@class=&quot;OneTimePassword---header4---1PWZR&quot;]</value>
      <webElementGuid>becf686e-2f0b-46af-98a9-3652b559fc96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div[2]/div/h4</value>
      <webElementGuid>0334803b-9294-4a4f-b768-787e9f91a050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 0.01'])[2]/following::h4[1]</value>
      <webElementGuid>abd198d3-df48-4ff8-867a-8b9daef23111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount'])[1]/following::h4[1]</value>
      <webElementGuid>f9fbae3a-c49d-49e2-9425-722f25c3ee68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[1]/preceding::h4[1]</value>
      <webElementGuid>25f066bf-1abe-4464-b8d3-8e7d59a9eb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check your Secure2u registered device and approve it within 50 seconds…']/parent::*</value>
      <webElementGuid>a91f0a82-e3e0-481e-9820-c989176b5717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>bf4080c1-2f6a-48c8-bbeb-322c75226a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Check your Secure2u registered device and approve it within 50 seconds…' or . = 'Check your Secure2u registered device and approve it within 50 seconds…')]</value>
      <webElementGuid>56f2e7a7-9eb9-4674-9039-ec1b46a644c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
