<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TRANSFERRM15.00</name>
   <tag></tag>
   <elementGuidId>ecfa9f4c-cc39-42aa-93ea-877178f5b860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d51d8b1b-86e8-4936-ad56-a93f194e1393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>16ecc898-eac1-40db-b42f-e75653fedd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ea38dd3-3d43-4eed-967c-89c79a32764f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSFERRM15.00</value>
      <webElementGuid>2bdb371d-9a4f-42ad-93e4-58272998a275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;Transactions---withSide---2taIP container-fluid Transactions---summaryContainer---1rNvj&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[2]/div[@class=&quot;row TransferOverseaTypeContainer---container---3myRn&quot;]/div[@class=&quot;TransferOverseaTypeContainer---fixContainer---24R7Q&quot;]/div[@class=&quot;col-xs-12 col-md-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 undefined&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-10&quot;]/div[@class=&quot;col-xs-12 col-sm-4 TransferOverseaTypeContainer---col-panel---3ajKW&quot;]/div[@class=&quot;TransferOverseaPanel---container---2vNrE&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-collapse collapse in&quot;]/div[@class=&quot;panel-body&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item&quot;]/div[@class=&quot;cls-info-wrapper&quot;]/div[@class=&quot;TransferOverseaPanel---btn-wrapper---C8xX3&quot;]/button[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>06b568d3-0b21-4274-baec-8d0046062ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>fb36e09e-d75b-4b59-a2f1-482d35372de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div[2]/div/ul/li[7]/div/div/button</value>
      <webElementGuid>2de3b150-92e7-4c49-94a3-da848fd239e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Duration'])[2]/following::button[1]</value>
      <webElementGuid>c5ad2ce6-0611-424a-9a7b-18914adaabd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Transfer Limit'])[2]/following::button[1]</value>
      <webElementGuid>1a685500-ba3a-4c37-bd2e-26a44c239289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/ul/li[7]/div/div/button</value>
      <webElementGuid>0efacceb-a2bb-4ecd-b7a7-29dd9c1645d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'TRANSFERRM15.00' or . = 'TRANSFERRM15.00')]</value>
      <webElementGuid>5219c9df-1dcc-437d-a612-76b5131a38bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
