<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RECIPIENTS DETAILS</name>
   <tag></tag>
   <elementGuidId>75efc156-df46-4f82-8b3b-4634ec37fb9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1 > div.panel-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29188a89-fd8e-4765-8d26-5755c8c02e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-heading</value>
      <webElementGuid>43ae2179-7ad8-4345-8168-72c2b466ba9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RECIPIENT'S DETAILS</value>
      <webElementGuid>fb1c3452-c38e-401f-b643-b6aa845ea635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;panel-heading&quot;]</value>
      <webElementGuid>471d8cd3-8db4-4de0-9685-91517f474fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div</value>
      <webElementGuid>16a6e72e-413f-4b78-8122-5372e1b16e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charitable Donations'])[2]/following::div[2]</value>
      <webElementGuid>8d1fb422-a9ad-49ea-b636-06f24bfcddda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inheritance'])[2]/following::div[3]</value>
      <webElementGuid>6f8ad955-676a-4361-b915-c3008170b792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::div[2]</value>
      <webElementGuid>dd2d4822-2c62-4ba2-9b98-f0b1d2fabc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::div[6]</value>
      <webElementGuid>864a4fba-3e56-43a3-9bf7-8cc64e6a7cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>325a4038-b402-48ed-99bd-59965eff4b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;RECIPIENT&quot; , &quot;'&quot; , &quot;S DETAILS&quot;) or . = concat(&quot;RECIPIENT&quot; , &quot;'&quot; , &quot;S DETAILS&quot;))]</value>
      <webElementGuid>41683bd1-b5c7-493f-8e3e-b505a4339afb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
