<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State_benState</name>
   <tag></tag>
   <elementGuidId>657b5996-67cd-40b9-b70f-e02c98da21e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benState</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddac8a1c-207e-45d2-b80c-a2aa24a4e9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>4c7230ed-2384-45c1-b257-e2e3b6a6fb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cac1d2fd-59d1-490c-9c08-7aa02331522b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>6f12837c-11cb-4b44-8128-7f395aea0a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benState</value>
      <webElementGuid>58550173-a4ac-4ff1-8a7d-c6f4c633d86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid State</value>
      <webElementGuid>bd37d930-8e3f-4e15-b2e6-6fd4c60a326b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benState&quot;)</value>
      <webElementGuid>b0fd6255-0bfc-4fe7-89f5-9658114001ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benState']</value>
      <webElementGuid>98e083cd-67dd-43d4-9fa4-481107fc6415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[9]/div/div[2]/input</value>
      <webElementGuid>393875c2-0103-4db6-9105-4e1d14c6c5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[9]/div/div[2]/input</value>
      <webElementGuid>bab95831-e48f-46b5-8661-7034474ccb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benState' and @title = 'Please Enter a Valid State']</value>
      <webElementGuid>858749fe-685d-4c6e-8355-f48dd74a475c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
