<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone No_benContactNationalNo</name>
   <tag></tag>
   <elementGuidId>3aef34d8-2d8d-4698-9b3e-233d7165e2a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benContactNationalNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benContactNationalNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e77d9f89-1d5a-424d-b883-3011f6d0b36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>1ee0274d-6bc8-4a67-a324-843fa3e75b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6532499d-f274-4285-9716-a501b1065be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>e6e86aec-e963-4933-aa29-567a88403b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benContactNationalNo</value>
      <webElementGuid>d2588ab4-47d8-47ce-84eb-913da9e74cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Phone No.</value>
      <webElementGuid>9a459bbd-b41c-490d-9399-0d126bdf55c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benContactNationalNo&quot;)</value>
      <webElementGuid>7cc0439e-ee56-4472-a051-c4a00e814dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benContactNationalNo']</value>
      <webElementGuid>0ba06f32-a75e-49fa-985e-c711f93adb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>80b46781-52fd-4083-a785-118c1b92e901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>d877f360-1090-4b8f-ab98-2d70bfd72aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benContactNationalNo' and @title = 'Please Enter a Valid Phone No.']</value>
      <webElementGuid>57cdb43f-d550-4d99-b649-e4f247ffd949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
