<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal Code_benPostalCode</name>
   <tag></tag>
   <elementGuidId>925a2d12-5e6a-40de-919d-7dc9799ad24c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benPostalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26bd725a-cb6a-44ac-8b44-1f8c4ba71bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>7322d52d-3048-4a96-b772-00c6bedaafdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f923cb4-473c-40cb-b7f9-8b28cf8803a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>388561ea-ff44-4bd3-805f-98d60eef92b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benPostalCode</value>
      <webElementGuid>78457d31-fdeb-428e-a020-1a7d4a647250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Postal Code</value>
      <webElementGuid>e6e96314-91d3-4080-8890-be8693074de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benPostalCode&quot;)</value>
      <webElementGuid>2bd26c14-eb8f-4602-b3aa-608c7f98c3ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benPostalCode']</value>
      <webElementGuid>de08e43e-a945-4a53-81a6-04c88b12db09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[7]/div/div[2]/input</value>
      <webElementGuid>9a4f06b9-8dc0-4ddd-bf70-4abdf20cecef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[7]/div/div[2]/input</value>
      <webElementGuid>7cd627b7-fd5f-4838-8e0d-0b9ba6065e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benPostalCode' and @title = 'Please Enter a Valid Postal Code']</value>
      <webElementGuid>c99e56ac-46b2-4bf3-9cc8-c3ec64dacd1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
