<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RM_CustomInputGroup---textInput---1X4_77e864</name>
   <tag></tag>
   <elementGuidId>1c740acc-d463-4d77-bafe-6c6b2558d314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.CustomInputGroup---textInput---1X446.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8a8e46f-6a9a-46a1-8bf0-1bc4f92b6f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0acfb291-85ba-409f-a525-617d0952cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CustomInputGroup---textInput---1X446 form-control</value>
      <webElementGuid>c9cb4469-5b1f-424d-90c2-b706c97e6f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;Transactions---withSide---2taIP container-fluid Transactions---summaryContainer---1rNvj&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[2]/div[@class=&quot;row TransferOverseaTypeContainer---container---3myRn&quot;]/div[@class=&quot;TransferOverseaTypeContainer---fixContainer---24R7Q&quot;]/div[@class=&quot;col-xs-12 col-md-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 undefined&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;CustomInputGroup---container---2Lt0m&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex-row&quot;]/div[@class=&quot;flex-col-xs-12 flex-col-sm flex-col-md flex-col-lg-5&quot;]/span[@class=&quot;input-group&quot;]/input[@class=&quot;CustomInputGroup---textInput---1X446 form-control&quot;]</value>
      <webElementGuid>ccb051ad-f291-4b4b-aa59-449ba62d9620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>cb46abc1-ac6d-4a63-a0d9-4dfe4dfac32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[2]/div[2]/div/div[2]/div/div/div/form/div/div/div/div/div/div/span/input</value>
      <webElementGuid>d17ce74c-f580-4987-88f0-31660f6a9f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>3a30ed1e-0d3e-41bb-9f17-285ed4c9e488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>263f5139-1d2d-49ba-a8b0-022b11805dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
