<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_benFirstName</name>
   <tag></tag>
   <elementGuidId>919db308-22c1-4459-afbb-d4365a35b83d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17b2b4af-fd77-49f0-af5b-4a407dbe71cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>6979f446-22b2-4f46-9925-e8b57bf2135a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a90ad56b-42cd-4502-868e-d8ff0e795eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>ba3ed2e5-2d77-4bd2-8106-c589280e8a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benFirstName</value>
      <webElementGuid>6329d69e-119b-40ee-ba55-f233dd0bcca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid First Name</value>
      <webElementGuid>826eb057-9610-402a-8097-f4c6de50be45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benFirstName&quot;)</value>
      <webElementGuid>dd3319f7-f246-4ad3-ad53-fa48cbbc3945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benFirstName']</value>
      <webElementGuid>57c9ad26-a9d6-4865-89ec-f5a2342dde91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>276047a1-7e87-447a-b171-37a7ab411452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>a99cfd5a-814b-40f9-b647-055243653d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benFirstName' and @title = 'Please Enter a Valid First Name']</value>
      <webElementGuid>b3a33cb9-2994-49ef-84d9-742decd68966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
