<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Receiver Country  Code_RenderSearchab_209348</name>
   <tag></tag>
   <elementGuidId>60641e17-4922-4bc8-9532-ffcaafcfc6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee27d5e6-a172-45e6-a8db-d2dda4398e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a56d0635-f17d-4124-99ef-e6e56db3742e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Select</value>
      <webElementGuid>f593a6f2-16a8-4271-a220-7725d921f025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RenderSearchableDropdown---paymentInput---21ojH</value>
      <webElementGuid>c8ef9fbd-31d9-48f2-b890-ac433d790409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a996c64b-f95a-4121-9a89-1dae33bcf9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;panel-collapse collapse in&quot;]/div[@class=&quot;panel-body&quot;]/div[4]/div[@class=&quot;row TransferModal---inputPair---2v4pK&quot;]/div[@class=&quot;col-sm-7&quot;]/div[@class=&quot;RenderSearchableDropdown---container---1MNpu TransferModal---containerClass---3Gy8x&quot;]/div[@class=&quot;RenderSearchableDropdown---dropdownHolder---3G3aH&quot;]/input[@class=&quot;RenderSearchableDropdown---paymentInput---21ojH&quot;]</value>
      <webElementGuid>fe4f0c24-1db6-4054-a63d-986e785e0e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[7]</value>
      <webElementGuid>8c2cb143-30bc-4a3b-9fa0-2bb840f04262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>9c2bcdb8-040a-43c4-8c40-b5d72e298313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>1255fb43-7d42-4ae2-8309-c7c1e27a217b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Please Select']</value>
      <webElementGuid>a21cf0a1-8141-4bcb-8bbb-f59b03184e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
