<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_benLastName</name>
   <tag></tag>
   <elementGuidId>9e7547f0-6212-4197-b8a6-de604637d305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96d1da94-e8d4-4eca-a14f-845db42a13a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>dd5a51a1-d460-4653-b72c-8c4fea77a65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4ba8d7a-52b7-4d88-9984-545edb132427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>1b929b43-c47e-4e61-996c-6f0e9c58afe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benLastName</value>
      <webElementGuid>9d76c3fa-e263-429d-905b-84beec5b50fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Last Name</value>
      <webElementGuid>ef6ee8de-535e-4879-b60a-276efb7703a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>U</value>
      <webElementGuid>b0172751-81cc-4109-ad3a-e6db6fe8fae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benLastName&quot;)</value>
      <webElementGuid>ddcebd28-0c69-4562-b61f-530c147c4f4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benLastName']</value>
      <webElementGuid>16e6626d-c2c8-4802-8ae4-a2c375f66c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>efc7e35b-ed52-44bd-87b8-ff017cce2c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>44cd7abc-5fd2-4193-83d1-e0e6d0136960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benLastName' and @title = 'Please Enter a Valid Last Name']</value>
      <webElementGuid>d4601af7-7f04-4c29-8926-3892205177b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
