<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City (Destination)_benCity</name>
   <tag></tag>
   <elementGuidId>1434c3de-6cf6-4a8d-8202-3106a2409529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='benCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f19a40f-7b4d-4e7d-8c6b-ef5185e154ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>019ceea7-34c3-4f5e-90a7-5ab82f244da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6582b60-d296-4d22-adbd-1054bd19a3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>fa3cf4f8-4094-497d-9818-ea22db23e6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benCity</value>
      <webElementGuid>11c97aed-2d79-4330-bdae-6c2c8d988adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid City (Destination)</value>
      <webElementGuid>96783ba0-f08b-4ada-9261-98553e2cdb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benCity&quot;)</value>
      <webElementGuid>0828223e-c3d4-45ba-8fc7-f3c804322ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='benCity']</value>
      <webElementGuid>5bbaf9d0-c9b6-41ef-aac1-29f6fa8b985b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[8]/div/div[2]/input</value>
      <webElementGuid>d1250afe-41e2-4ae9-b481-c1d1926a8f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[8]/div/div[2]/input</value>
      <webElementGuid>7a9b4a5d-5699-49a1-baf3-9c2d51e61ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'benCity' and @title = 'Please Enter a Valid City (Destination)']</value>
      <webElementGuid>4c934d15-3ed9-49f3-a8e5-d05e5dfb063f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
