<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jalan Sempurna</name>
   <tag></tag>
   <elementGuidId>6d525532-274a-40b2-af56-f98a5c6b4297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='benStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d4822084-1383-4ecb-8d03-2c9877c6b582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---textArea---2iiJf</value>
      <webElementGuid>12949cc5-c8bb-4ad5-a0a3-aa55264c9a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benStreet</value>
      <webElementGuid>875ae5bc-8e6d-4ff7-9332-1fe2368e88e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f90a5c95-49b9-4fbd-95c5-0baec4b302f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f153616-1c05-4426-88d3-8687a9157124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalan Sempurna</value>
      <webElementGuid>cea0f2a8-3dbd-4596-a5b2-68c8ccdd7077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benStreet&quot;)</value>
      <webElementGuid>39ddd18c-b52d-4427-9ee5-34e2d5cd5cbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='benStreet']</value>
      <webElementGuid>da7ef68d-395c-4d70-8c83-b48e5d2a55c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>1b36e203-75ee-4a7a-838e-910ab4b5baa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 1'])[1]/following::textarea[1]</value>
      <webElementGuid>acd86ce5-e683-464d-8a39-cb8f743d9297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::textarea[1]</value>
      <webElementGuid>3651e591-c2a9-43f2-8d11-94930ea2b2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 2'])[1]/preceding::textarea[1]</value>
      <webElementGuid>10775548-4bc6-49ec-8ec8-f206f81dc414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::textarea[2]</value>
      <webElementGuid>604fbbb3-bba3-45b7-8a30-0b8487a74075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jalan Sempurna']/parent::*</value>
      <webElementGuid>49e63c78-480e-457a-a2a3-3b63040e7b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>f53a8211-27f5-4001-89ee-2e33545db7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'benStreet' and (text() = 'Jalan Sempurna' or . = 'Jalan Sempurna')]</value>
      <webElementGuid>d22e0ad2-3a60-492b-9a3c-643f860d2932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
