<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jalan Sempur</name>
   <tag></tag>
   <elementGuidId>017508d5-2c21-4142-b440-aacaa78babdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='benStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c5849e66-140c-4f59-9cef-308fa237b435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---textArea---2iiJf</value>
      <webElementGuid>80a9e43f-35d3-4453-909b-93122e08c080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benStreet</value>
      <webElementGuid>c6f8bd21-8f0c-4795-8041-310bcb0c14d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8928be78-d563-42cf-a35f-5293f657a581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>619f7e59-5cbc-402f-9283-f37acdbbb0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalan Sempur</value>
      <webElementGuid>6f5a7372-ebea-4332-9f10-a926a99e47b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benStreet&quot;)</value>
      <webElementGuid>9ef0663e-27cf-424c-96e8-e4a01383aba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='benStreet']</value>
      <webElementGuid>61a2ed39-4156-400d-864c-f0afea01e1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>da21b2c4-4d88-4410-8e3d-13348373394d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 1'])[1]/following::textarea[1]</value>
      <webElementGuid>de613f57-a153-4ce0-a990-26afc7d96c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::textarea[1]</value>
      <webElementGuid>cdf2da1e-1eab-4550-95a1-ae9ad0c45100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 2'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4576384f-5c08-46ea-8d33-0f8751a7f2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::textarea[2]</value>
      <webElementGuid>815ca431-9fcf-4870-94dc-61b90bb46c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jalan Sempur']/parent::*</value>
      <webElementGuid>5eaf256e-bf05-44c6-a463-ea70b7ce3a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>5393caf9-b807-4a6d-a463-02925d44e91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'benStreet' and (text() = 'Jalan Sempur' or . = 'Jalan Sempur')]</value>
      <webElementGuid>53f60821-4466-4251-9c38-d548ba87f291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
