<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jalan Sempurna Lubuk_1</name>
   <tag></tag>
   <elementGuidId>de0bae5f-b395-46a0-8342-474d72de30c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#benStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='benStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>750850b0-98c6-421c-a89d-2633a2e0eae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---textArea---2iiJf</value>
      <webElementGuid>245864b6-b0ab-412c-8739-3eeae54d295b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>benStreet</value>
      <webElementGuid>2019f99d-3d54-422e-925f-7175d50ff352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>1f96f62f-393c-4bef-92cd-fd440f5e5b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a05f910d-c0d1-438f-a09d-6ef87e12fcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalan Sempurna Lubuk </value>
      <webElementGuid>3b2b0223-b62f-4524-8b41-5adbaeeff494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;benStreet&quot;)</value>
      <webElementGuid>14c2266e-ed6d-4151-ae4e-a04e5f44c3b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='benStreet']</value>
      <webElementGuid>7d70e674-2377-48bd-bb6b-4eb47c53bfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>cfa35089-3d35-4464-a566-2985258bc5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 1'])[1]/following::textarea[1]</value>
      <webElementGuid>21abd7d2-8efa-4e8b-a91e-aec1c6eaac74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::textarea[1]</value>
      <webElementGuid>018f5cb3-129f-41cf-881c-4e3e0e3db77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Line 2'])[1]/preceding::textarea[1]</value>
      <webElementGuid>f7aa73ba-f6ab-4a96-bb89-aaa750d6b19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::textarea[2]</value>
      <webElementGuid>24c1fba7-9dcc-4094-938e-2696f240a258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jalan Sempurna Lubuk']/parent::*</value>
      <webElementGuid>1022869c-8307-4030-81fd-bc0d7e0164ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]/div/div[2]/textarea</value>
      <webElementGuid>ee3fad5c-ed2e-47ac-b6e9-ad913801c487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'benStreet' and (text() = 'Jalan Sempurna Lubuk ' or . = 'Jalan Sempurna Lubuk ')]</value>
      <webElementGuid>d8279210-5412-474f-b055-bd50f9b76bb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
